version: "3"
services:
  web:
    image: kevineye/ddc-sample-hovers
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 10M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

